name: Check for Secrets

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install git-secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y git-secrets

      - name: Initialize git-secrets
        run: git secrets --install

      - name: Add AWS and other common patterns
        run: |
          git secrets --register-aws
          git secrets --add 'AWS'
          git secrets --add 'SECRET_KEY'
          git secrets --add 'PASSWORD'
          git secrets --add 'PRIVATE_KEY'

      - name: Scan repository for secrets
        run: git secrets --scan
